`Numpy` is a library which helps with scienftific compuatation .
It provides support for `arrays and matrices along with other mathematical functions.`

In [1]:
import numpy as np

# create a 1D array

array1 = np.array([1,2,3,4,5]) # passed numbers can be list or tuple
print(array1)
print(type(array1))
print(array1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
#Reshaping the array
# .reshape(r,c) -->this will reshape given 1 dimensional matrix to multi dimension
array2 = array1.reshape(5,1)
print(array2)
print(array2.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


`np.arange(start,stop,step)` will form an array from start to stop with step differnce between the elements.

In [6]:
array3 = np.arange(2,10,2)
print(array3) #[2 4 6 8] strat =2 ,stop =10 ,differnce =2
print(array3.reshape(2,2)) 

[2 4 6 8]
[[2 4]
 [6 8]]


`np.ones(shape)` can be used for getting maatrix with just '1' as its elements. <br>
`np.zeroes(shape)` can be used for getting matrix with just '0' as as its elements.<br>
`np.eye(rows)` will get the identity matruix.<br>


In [12]:
print(np.ones((5,5)))
print()
print(np.zeros((5,5)))
print()
print(np.eye(5))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


suppose `arr` is the defined matrix <br>
<o> <b>arr.shape</b></o> will give the shape of the matrix. <br>
<o><b>arr.ndim </b></o> will give the dimensio of the matrix .<br>
<o><b> arr.size </b></o> will give the array size <br>
<o><b> arr.dtype </b></o> will give the dtype of the array <br>
<o><b> arr.itemsize </b></o>will give the number of elemnts an array <br>

In [16]:
array4 = np.ones((5,6))
print(array4.shape , " arrays shape")
print(array4.size ," arrays size")
print(array4.dtype ," arrays dtype")
print(array4.ndim ," arrays dimension")

(5, 6)  arrays shape
30  arrays size
float64  arrays dtype
2  arrays dimension


Numpy vectorized operation works element wise.

In [17]:
#numpy vectorized operation
arr1 = np.array([5,10,15,20,25])
arr2 = np.array([1,2,3,4,5])

#Element wise addition
print("Addition ",arr1 + arr2)

#Element wise substraction
print("Subtraction ",arr1 - arr2)

#Element wise multiplication
print("Multiplication ",arr2 * arr1)

#Elemnt wise Division
print("Division ",arr1 /arr2)

Addition  [ 6 12 18 24 30]
Subtraction  [ 4  8 12 16 20]
Multiplication  [  5  20  45  80 125]
Division  [5. 5. 5. 5. 5.]


In [18]:
 ## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [23]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)
print("\n",arr[1:,2:]) #first index refers rows and second one columns

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 [[ 7  8]
 [11 12]]


In [24]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [25]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
